### ISSUE TITLE
Cannot add book

### ISSUE THREAD

**Issue by AustinDeric** [dasniko/keycloak-reactjs-demo#11]
I am able to successfully login to the app using my keycloak server hosted on aws using ssl.  However I cannot add a book.

The web console give the following error:
```
austinderic added the book testbook
XML Parsing Error: syntax error
Location: http://localhost:3000/demo/books
Line Number 1, Column 1:
books:1:1
Error: Request failed with status code 500
```

the terminal where i launched the `npm run start` command gives the following proxy error:
```
Proxy error: Could not proxy request /demo/books from localhost:3000 to http://localhost:8081.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

[HPM] Error occurred while trying to proxy request /demo/books from localhost:3000 to http://localhost:8081 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I really love this repo, thanks!

**Comment by dasniko** [comment]
Do you have a backend server running at `localhost:8081`?
If no, that's the problem.
If yes, there seems to be the problem. ;-)

I'm using https://github.com/dasniko/keycloak-javaee-demo as backend, but it can be any server which serves the right format. I should have mentioned this.

If I find the time, I'll provide a Swagger spec of how the backend should be build up.

**Comment by AustinDeric** [comment]
By backend did you mean a keycloak server?  If so then no, i am running it on aws and access it via https.

**Comment by dasniko** [comment]
No, with backend I mean the service where the app receives its data from and posts new books. That's what the functions in `modules/books.js` do. They communicate with the same host as the app is delivered (`localhost:3000`) and that's why there is a proxy configured in the `package.json` to proxy theses requests to another service.

As mentioned, I'll provide a Swagger file for this backend soon.
Perhaps I'll also provide a complete service (powered serverless w/ AWS API Gateway and Lambda) which can be used to run the app, so that you don't have to deploy another one.

**Comment by dasniko** [comment]
I've added the swagger spec with https://github.com/dasniko/keycloak-reactjs-demo/commit/e7b3eb2951c70f3f875dc2c62530ed0d5cc5f9e7
The README is also updated.

**Comment by dasniko** [comment]
closing, as you don't need the javaee backend anymore...
