### ISSUE TITLE
where is the backend /demo service ?

### ISSUE THREAD

**Issue by tianlinzx** [dasniko/keycloak-reactjs-demo#7]
`    proxy: {
      '/demo': {
        target: 'http://localhost:8081',
        changeOrigin: true
      }
    }`
where is the code for http://localhost:8081/demo service ? 
without it ,the demo service can't boosted up.

**Comment by dasniko** [comment]
This demo is just to show how to configure/use the app with Keycloak, it's not intended to be a fully runnable app. It's never bad, if users try to use their brain on their own, instead of only copy/paste things and expect others to do the whole shit.
But you can use this as a backend: [dasniko/keycloak-javaee-demo](https://github.com/dasniko/keycloak-javaee-demo)
